# Prompt for generating a real world stateful agent framework configuration:
#
# You are a <role> with the purpose of <purpose>.
#
# Please first investigate and create a plan for generating a real world stateful agent framework configuration using using the role that you have declared. Generate as many states as required that a professional in this space would apply to a real situation. Also generate the HUD and any other parts of the configuration to ensure that this agent config includes all of the relevant information and design to achieve your purpose.
# Use state names that reflect its purpose.
#
# <Insert any other details that are relevant to the agents role and purpsoe.
#
# Use the following configuration template as the structure of the configuration.



persona:
  name: "<agent name>"  # The name of your agent.
  description: |
    <Enter a brief description of the agent.>
  purpose: |
    <Enter the purpose of the agent.>

states:
  example_state_1:
    purpose: |
      <Enter the purpose of this state.>
    output_format: |
      **Example Data:** <states.example_state_1.goals.gather_initial_info.data.initial_info>
    goals:
      example_1_goal:
        goal: |
          <Enter the goal of this state.>
        data:
          example_1_variable: "type <data_type>: <Enter the data description here>"
      example_1_content:
        goal: |
          Compile and format the gathered information according to the state purpose and goals.
        data:
          example_1_answer: "type string: <Place the final information according to the state purpose and goals>"

  example_state_2:
    purpose: |
      <Enter the purpose of this state.>
    output_format: |
      **Example Data:** <states.example_state_2.goals.example_2_content.data.example_2_answer>
    goals:
      example_2_goal:
        goal: |
          <Enter the goal of this state.>
        data:
          example_2_variable: "type <data_type>: <Enter the data description here>"
      example_2_content:
        goal: |
          <Compile and format the gathered information according to the state purpose and goals.>
        data:
          example_1_answer: "type string: <Place the final information according to the state purpose and goals>"

goals:
  framework:
    goal1: "<Enter the main goals of the assistant.>"

hud:
  content_markdown: |
    #### Example 1
    <states.example_state_1.goals.example_1_content.data.example_1_answer>

    #### Example 2
    <states.example_state_2.goals.example_2_content.data.example_2_answer>

framework_settings:
  starting_state: "example_state_1"  # The state from which the process starts.
  reasoning_agent: "single"       # Options: single | socratic
  reasoning_agents_config:
    single:
      model: "gpt-4o-mini"
      openai_config:
        temperature: 0.5
        top_p: 1.0
        presence_penalty: 0.0