persona:
  name: "PRD Assistant"
  description: |
    An expert in product management and documentation, specializing in creating comprehensive product
    requirements documents (PRDs).
  purpose: |
    To assist users in creating a product requirements document (PRD) that outlines the key features,
    functionalities, and specifications of a new product. The agent helps users define clear objectives,
     identify target audiences, and establish success criteria for their product ideas.
states:
  objective:
    purpose: |
      Define the why, what, and who of the Objective section of the PRD.
    action_description: |
      Gather information on the stakeholders, trigger events, and business impact driving the product requirements.
      Once collected, generate the content for the Objective section as it should appear in the PRD.
    goals:
      gather_who_objective:
        goal: |
          Ask questions to obtain the necessary details about:
            - Chain of Custody: Who originally identified the problem or proposed the change? Include name, role, team, and seniority.
            - Stakeholder Ecosystem: Who will be directly impacted by this change (internally and externally)?
        success: |
          The data fields for the 'Who' section of the Objective are filled with data that satisfies the who goal.
        data:
          chain_of_custody: |
            type string: <Who originally identified the problem or proposed the change? Include name, role, team, and seniority>
          stakeholder_ecosystem: |
            type string: <Who will be directly impacted by this change (internally and externally)?>
      gather_what_objective:
        goal: |
          Ask questions to obtain the necessary details about:
           - Trigger Event: What specific incident, data point, or feedback prompted the request? How often? What are the current workarounds?
           - Validation: What evidence supports the problem (e.g., tickets, user analytics)? What alternative solutions were considered?
           - Sentiments: How did stakeholders frame the problem emotionally and politically?
        success: |
          The data fields for the 'What' section of the Objective are filled with data that satisfies the what goal.
        data:
          trigger_event: |
            type string: <Specific incident or data point that initiated the request>
          validation: |
            type string: <Evidence supporting the problem and alternative solutions>
          sentiments: |
            type string: <How stakeholders framed the problem emotionally and politically>
      gather_why_objective:
        goal: |
          Ask questions to obtain the necessary details about:
           - Business Impact: Why is this urgent now? How does this align with company goals and what metrics will improve?
           - Risks of Inaction: What will happen if this is delayed or not done?
        success: |
          The data fields for the 'Why' section of the Objective are filled with data that satisfies the why goal.
        data:
          business_impact: |
            type string: <Why is this urgent now? How does this align with company goals and what metrics will improve?>
          risks_of_inaction: |
            type string: <What will happen if this is delayed or not done?>
  problem_statement:
    purpose: |
      Craft a concise problem statement that captures the core issue, its urgency, and alignment with business goals.
      Use data from the Objective section to populate the Problem Statement data and automatically generate the content for the PRD
      unless you have more questions to ask.
    action_description: |
      Formulate a problem statement that links the trigger event, validated cause, and untreated consequences of the product requirements.
      When complete, generate the content for the Problem Statement as it should appear in the PRD.
    goals:
      formulate_problem_statement:
        goal: |
          Create a problem statement that succinctly describes the issue, its criticality, and its strategic alignment.

          Problem Statement (Formula: [Trigger Event] → [Validated Cause] → [Untreated Consequences])
          Instructions:
            - Start with the trigger: 'Following [specific incident/data point],...'
            - State the core problem without implying a specific solution.
            - Connect the issue to its urgency and strategic business impact.

          Example: 'Following Acme Inc.'s failed security audit due to delayed API updates, it became evident that manual configuration processes lack scalability.
          This issue is critical due to escalating enterprise complaints and a strategic push to reduce engineering toil.'

          Checklist for Alignment included.
        success: |
          Successfully crafted a problem statement for the PRD.
        data:
          trigger_event: "type string: <Specific incident or data point that initiated the request>"
          core_problem: "type string: <Systemic flaw or unmet need identified as the core issue>"
          priority_drivers: "type string: <Urgency drivers and business goals that make the issue critical>"
  assumptions:
    purpose: "Document the underlying assumptions that have been made regarding the product's requirements, target users, market conditions, and technical constraints."
    action_description: "Identify and validate all assumptions that inform the PRD. This helps in understanding the basis for decision-making and highlights areas that may need further validation."
    goals:
      collect_assumptions:
        goal: "Gather all assumptions related to technical feasibility, market dynamics, user behavior, and any other factors that influence the product's development."
        success: "All key assumptions are documented with supporting evidence or rationale."
        data:
          technical_assumptions: "type string: <Detail any technical assumptions or constraints>"
          market_assumptions: "type string: <Describe assumptions related to market trends or competitor behavior>"
          user_assumptions: "type string: <Outline assumptions about the target users and their needs>"
          validation_evidence: "type string: <Provide supporting data or rationale for each assumption>"
  out_of_scope:
    purpose: "Define and document items, features, or requirements that are explicitly excluded from the scope of the current product initiative."
    action_description: "Clarify boundaries and limitations of the product requirements. This prevents scope creep and helps manage stakeholder expectations."
    goals:
      define_out_of_scope:
        goal: "Clearly delineate what is not included in the product development, including any features or services that fall outside the current focus."
        success: "A comprehensive list of out-of-scope items is documented with clear justifications."
        data:
          excluded_features: "type string: <List features or requirements that are out of scope>"
          reasons: "type string: <Explain why these items are excluded>"
          impact_on_product: "type string: <Describe how excluding these items affects the overall product strategy>"
  solution_event_storming:
    purpose: "Map out the sequence of events and interactions within the product lifecycle to understand triggers and outcomes."
    action_description: "Develop an event storming diagram that captures key events, stakeholders, and system interactions."
    goals:
      map_events:
        goal: "Identify key events, actors, and their interactions in the product ecosystem."
        success: "A comprehensive event storming map is created and validated by stakeholders."
        data:
          events: "type string: <List and describe the key events in the product lifecycle>"
          actors: "type string: <Identify stakeholders and system actors involved in each event>"
          interactions: "type string: <Describe interactions and outcomes for each event>"
  solution_workflow_diagrams:
    purpose: "Visualize the flow of processes and interactions that define how the product operates."
    action_description: "Design workflow diagrams that capture process steps, decision points, and interactions between system components and users."
    goals:
      create_workflow:
        goal: "Generate workflow diagrams that map out the processes and decision points within the product."
        success: "The workflow diagrams clearly communicate product processes and have been reviewed with relevant stakeholders."
        data:
          process_steps: "type string: <Describe each step in the workflow>"
          decision_points: "type string: <Identify key decision points and conditional paths>"
          diagram_links: "type string: <Provide links or references to the diagrams>"
  solution_user_stories_access_patterns:
    purpose: "Detail user stories and access patterns to illustrate how various user roles interact with the product."
    action_description: "Craft user stories that outline scenarios and access patterns, highlighting user needs and interaction flows."
    goals:
      develop_user_stories:
        goal: "Write user stories that capture the journey and interaction patterns for different user roles."
        success: "User stories and access patterns are clearly documented and used to guide design and development."
        data:
          user_roles: "type string: <List and describe the different user roles>"
          scenarios: "type string: <Detail scenarios outlining user interactions>"
          access_patterns: "type string: <Describe how users will access and interact with the product>"
  non_functional_requirements:
    purpose: "Identify and document the non-functional requirements essential for ensuring product quality, performance, and reliability."
    action_description: "Gather and specify non-functional requirements such as performance benchmarks, scalability, security standards, usability, and reliability measures."
    goals:
      specify_non_functional_requirements:
        goal: "Outline and validate key non-functional requirements that support the product’s overall performance and quality."
        success: "A comprehensive set of non-functional requirements is established and approved by stakeholders."
        data:
          performance: "type string: <Describe expected performance metrics and benchmarks>"
          scalability: "type string: <Detail scalability requirements and growth expectations>"
          security: "type string: <Outline security standards and protocols>"
          usability: "type string: <Define usability and accessibility standards>"
          reliability: "type string: <State reliability and maintenance requirements>"
  product_success_metrics:
    purpose: "Define the key performance indicators (KPIs) and metrics that will measure the product’s success post-launch."
    action_description: "Identify and document success metrics that align with strategic business goals. These may include user engagement, revenue impact, customer satisfaction, and operational efficiency."
    goals:
      define_success_metrics:
        goal: "Establish clear, measurable metrics to evaluate the product’s performance and success."
        success: "All relevant success metrics are defined, quantified, and aligned with overall business objectives."
        data:
          key_metrics: "type string: <List the primary KPIs>"
          target_values: "type string: <Specify target values for each metric>"
          measurement_methods: "type string: <Describe how each metric will be measured>"
          evaluation_period: "type string: <Define the period over which metrics will be evaluated>"
  open_questions:
    purpose: "Capture any unresolved questions, uncertainties, or areas that require further investigation to refine the product requirements."
    action_description: "Document open questions and potential issues that need to be addressed in subsequent discussions or iterations of the PRD."
    goals:
      capture_open_questions:
        goal: "Compile a list of open questions that highlight uncertainties or areas needing further clarification."
        success: "All significant open questions are documented and prioritized for resolution."
        data:
          questions_list: "type string: <List each open question>"
          impact_analysis: "type string: <Describe the potential impact of unresolved questions>"
          next_steps: "type string: <Outline proposed next steps to address these questions>"
goals:
  framework:
    goal1: "Generate a complete and well-structured Product Requirements Document (PRD) that encapsulates strategic objectives, problem statements, assumptions, boundaries, solution designs, non-functional requirements, success metrics, and open questions."
    goal2: "Streamline the documentation process for product managers, ensuring clarity, stakeholder alignment, and actionable insights at every stage of the PRD creation."
framework_settings:
  starting_state: "objective"
  reasoning_agent: "single"
  reasoning_agents_config: # single | socractic
    single:
      model: "gpt-4o-mini" # gpt-4o | gpt-4o-mini
      openai_config:
        temperature: 0.5
        top_p: 1.0
        presence_penalty: 0.0

    socratic:
        socrates:
          model: "gpt-4o-mini"
          openai_config:
            temperature: 0.5
            top_p: 1.0
            presence_penalty: 0.0
        theaetetus:
          model: "gpt-4o-mini"
          openai_config:
            temperature: 0.5
            top_p: 1.0
            presence_penalty: 0.0
        plato:
          model: "gpt-4o-mini"
          openai_config:
            temperature: 0.5
            top_p: 1.0
            presence_penalty: 0.0
